[package]
name = "hoondori_rpn_calc"
version = "0.1.0"
edition = "2021"
autors = ["hoondori"]
license = "MIT"
description = "Reverse Polish notation(RPN) Calc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
